Homework2
nekdfl/GB-js1 pull request #2
Opened 2021-01-27 07:10 UTC by nekdfl

Задания 1-8.

2021-01-27 14:44 UTC, Om1X requested changes

2021-01-27 14:44 UTC, Om1X commented on homework2/script/task3.js
> +    if (a > 0 && b > 0) {
забыли про равенство нулю

2021-01-27 14:44 UTC, Om1X commented on homework2/script/task3.js
> +    } else if ((a > 0 && b < 0) || (a < 0) && (b > 0)) {
здесь можно просто else и опустить условие, т.к. оно будет уже следствие непопадания в первые два

2021-01-27 14:44 UTC, Om1X commented on homework2/script/task6.js
> +    return res;
Дабы не плодить лишних переменных, лучше из кейсов делать `return sum(arg1, arg2)`

2021-02-02 08:23 UTC, nekdfl commented on homework2/script/task6.js
> +    return res;
здесь не будет лишних переменных. в каждом case есть break. Время жизни переменной в абсолютном времени больше всего на 1 инструкцию или я не прав. Следуюя "Чистому коду" Р. Мартина - делал поведение кода функции более очевидным. Возврат в конце функции.

2021-02-02 08:23 UTC, merged

2021-02-02 08:24 UTC, nekdfl commented on homework2/script/task3.js
> +    if (a > 0 && b > 0) {
В условии ничего не сказано про равенство чисел.